### ISSUE TITLE
Customer Risk REST API

### ISSUE THREAD

**Issue by JPerzanowski** [JPerzanowski/customer-risk-notifier#2]
# Definition of Done

- [x] Rest API that returns information about the latest customer data(/api/customer/{customer_id} )
- [x] Rest API returns historical data from a specific day, if an additional "date" parameter is provided (/api/customer/{customer_id}?date={date})
- [x] POST notes about the client in JSON
- [x] Ability to read saved notes about the customer, taking into account the date range (GET /api/customer/customerId}/note?since={dateSince}&until={dateUntil}

# User Story

As the user I want to get data about the Customer's risks via REST API, so that I could manage that data.

# Description

For the Customer's data and notes the system would provide the following REST API:
- `GET`: `/api/customer/{customer_id}`,
- `GET`: `/api/customer/{customer_id}?date={date}`,
- `POST`: `/api/customer/{customer_id}/note`,
- `GET`: `/api/customer/customerId}/note?since={dateSince}&until={dateUnitl}`.

The detailed description is provided under the tasks.

# Tasks List

- [x] #9
- [x] #10
